### ISSUE TITLE
refactor: convert to classes

### ISSUE THREAD

**Issue by TGTGamer** [Videndum/super-labeler-action#11]
Refactor the code to use classes instead of exported const. 

# Tasks to complete @Westy456 

- [ ] Complete the developer onboarding: [here](https://github.com/Videndum/.devcontainer)

# Tasks to complete @TGTGamer 
- [x] Rework imports and exports in `./src/index.ts` and `./src/superLabeler.ts`

# Tasks for either to complete
- [x] Move all `interface`
- [x] Move `syncLabels` to `superLabeler` class
- [x] Move `./src/parseContext.ts` to `.src/superLabeler.ts` and merge into class `SuperLabeler.ts`
- [x] Move `context` class to `./src/utils.ts`
